#version 430 core
layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

// We use binding 0 for both read and write
layout(std430, binding = 0) buffer Parameters { float P[]; };
layout(std430, binding = 1) buffer Gradients  { float G[]; };

uniform float u_learning_rate;
uniform int u_element_count;

void main() {
    uint index = gl_GlobalInvocationID.x;

    if (index >= u_element_count) {
        return;
    }

    P[index] -= u_learning_rate * G[index];
}